// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfd7Z6uow0Z8wwXpguNvaHCp6bbKDNsmI',
    appId: '1:376097597556:web:feb6e80a4836f679628921',
    messagingSenderId: '376097597556',
    projectId: 'doa-mais-36ac6',
    authDomain: 'doa-mais-36ac6.firebaseapp.com',
    storageBucket: 'doa-mais-36ac6.firebasestorage.app',
    measurementId: 'G-S895PDF7BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCez8dkjibCWRcee2jhJJ3hl35P0PVoy60',
    appId: '1:376097597556:android:777372d7785a1b3c628921',
    messagingSenderId: '376097597556',
    projectId: 'doa-mais-36ac6',
    storageBucket: 'doa-mais-36ac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKI0YGNgTwh1Q0sCjxW7YKbkGZsHkiGQo',
    appId: '1:376097597556:ios:7093e75f1d8a0cad628921',
    messagingSenderId: '376097597556',
    projectId: 'doa-mais-36ac6',
    storageBucket: 'doa-mais-36ac6.firebasestorage.app',
    iosBundleId: 'com.example.doaPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKI0YGNgTwh1Q0sCjxW7YKbkGZsHkiGQo',
    appId: '1:376097597556:ios:7093e75f1d8a0cad628921',
    messagingSenderId: '376097597556',
    projectId: 'doa-mais-36ac6',
    storageBucket: 'doa-mais-36ac6.firebasestorage.app',
    iosBundleId: 'com.example.doaPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfd7Z6uow0Z8wwXpguNvaHCp6bbKDNsmI',
    appId: '1:376097597556:web:daa1a4676371a88c628921',
    messagingSenderId: '376097597556',
    projectId: 'doa-mais-36ac6',
    authDomain: 'doa-mais-36ac6.firebaseapp.com',
    storageBucket: 'doa-mais-36ac6.firebasestorage.app',
    measurementId: 'G-5WKLGC0QLT',
  );
}
